import Head from 'next/head'
import Image from 'next/image'
import { HeroLink } from '../components/HeroLink'
import { Br2 } from '../components/Br2'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faGithub, faLinkedinIn } from '@fortawesome/free-brands-svg-icons'

export default function Home() {
  
  return (
    <>
    <Head>
        <title>Aaron Brunet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='min-h-screen p-12 border-t-4 border-blue-600'>
        <div className='flex flex-row'>
        <div className='justify-center self-center align-middle'>
          <h1 className='pb-8 title-font inline-block'>Hi, I'm Aaron</h1><span className='text-5xl inline-block cursor-pointer hover:animate-wiggle'>👋</span>
          <p className='text-xl w-3/5'>
          I'm a developer based in Orlando, Florida, with a special interest in emerging technologies and the changing face of the web.
          <Br2 />
          You can connect with me on <HeroLink href='https://www.linkedin.com/in/aaronwbrunet/' classes='border-[#0a66c2]'>LinkedIn</HeroLink>, or check out my <HeroLink href='https://github.com/aaronbrunet' classes='border-yellow-600'>GitHub</HeroLink> to see what I've been working on.
          <br/>
          I'm currently working for <HeroLink href='https://www.servicenow.com/' classes='border-[#81b5a1]'>ServiceNow</HeroLink> as a Performance Engineer.
          <Br2 />
          Think I should join your team? Shoot me an <HeroLink href='mailto:contact@aaronbru.net' classes='border-red-600'>email</HeroLink>!</p>
               
        </div>
        <div className=''>Right Column</div> 
        </div>
        <div className='py-12 grid'>
            <h3 className='subtitle-font pb-8'>Tools & Technologies</h3>
              <div className='max-w-5xl grid gap-4 xs:grid-cols-2 xs:p-8 md:grid-cols-4 lg:gap-6'>
                <div className='grid-item'>Grid</div>
                <div className='grid-item'>Grid</div>
                <div className='grid-item'>Grid</div>
              </div>
          </div>
        <div className='py-12 grid'>
            <h3 className='subtitle-font pb-8'>Projects</h3>
              <div className='max-w-5xl grid gap-4 xs:grid-cols-2 xs:p-8 md:grid-cols-4 lg:gap-6'>
                <div className='grid-item'>Grid</div>
                <div className='grid-item'>Grid</div>
                <div className='grid-item'>Grid</div>
              </div>
          </div>
      </main>

      <footer className='w-full justify-center flex'>
        <a
          href="https://aaronbru.net"
          target="_blank"
          rel="noopener noreferrer"
        >          
          Aaron Brunet © {new Date().getFullYear()}
        </a>
      </footer>
</>)}
